language: php
branches:
  only:
  - dev
notifications:
  email:
    on_success: never
    on_failure: change
php:
- 5.6
env:
- WP_VERSION=latest WP_MULTISITE=1
before_install:
- composer install --dev
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
after_success:
- bash <(curl -s https://codecov.io/bash)
